use std::env;
use std::fs;
use std::path::PathBuf;

use crate::error::AppResult;
use crate::model::{Entry, Scope};
use crate::path_merge::{PathCase, merge_path};
use crate::store::EnvStore;

const PATH_SEPARATOR: char = ':';

pub struct UnixFileStore {
    scope: Scope,
}

impl UnixFileStore {
    pub fn new(scope: Scope) -> Self {
        Self { scope }
    }

    fn entries_path(&self) -> AppResult<PathBuf> {
        Ok(match self.scope {
            Scope::User => config_dir()?.join(format!("entries_{}.json", self.scope.label())),
            Scope::System => PathBuf::from("/etc/path_control/entries_system.json"),
        })
    }

    fn profile_path(&self) -> AppResult<PathBuf> {
        Ok(match self.scope {
            Scope::User => config_dir()?.join("path_control.sh"),
            Scope::System => PathBuf::from("/etc/profile.d/path_control.sh"),
        })
    }
}

impl EnvStore for UnixFileStore {
    fn load_entries(&self) -> AppResult<Vec<Entry>> {
        let path = self.entries_path()?;
        if !path.exists() {
            return Ok(Vec::new());
        }

        let raw = fs::read_to_string(path)?;
        if raw.trim().is_empty() {
            return Ok(Vec::new());
        }

        Ok(serde_json::from_str(&raw)?)
    }

    fn load_path(&self) -> AppResult<String> {
        Ok(match self.scope {
            Scope::User => env::var("PATH").unwrap_or_default(),
            Scope::System => fs::read_to_string(self.profile_path()?)
                .ok()
                .and_then(|raw| parse_exported_path(&raw))
                .unwrap_or_default(),
        })
    }

    fn save_path(&self, value: &str) -> AppResult<()> {
        let path = self.profile_path()?;
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }

        fs::write(
            path,
            format!(
                "# Generated by path_control. Do not edit this file manually.\nexport PATH=\"{}\"\n",
                escape_shell_double_quoted(value)
            ),
        )?;
        Ok(())
    }

    fn save_entries(&self, entries: &[Entry]) -> AppResult<()> {
        let path = self.entries_path()?;
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, serde_json::to_string(entries)?)?;
        Ok(())
    }

    fn apply_path(&self, entries: &[Entry]) -> AppResult<()> {
        let current = env::var("PATH").unwrap_or_default();
        let next = merge_path(&current, entries, PATH_SEPARATOR, PathCase::Sensitive);
        self.save_path(&next)
    }
}

fn config_dir() -> AppResult<PathBuf> {
    if let Some(config_home) = env::var_os("XDG_CONFIG_HOME") {
        return Ok(PathBuf::from(config_home).join("path_control"));
    }

    let home = env::var_os("HOME").ok_or("HOME is not set")?;
    Ok(PathBuf::from(home).join(".config").join("path_control"))
}

fn escape_shell_double_quoted(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('$', "\\$")
        .replace('`', "\\`")
}

fn parse_exported_path(raw: &str) -> Option<String> {
    raw.lines().find_map(|line| {
        let value = line.trim().strip_prefix("export PATH=\"")?;
        Some(value.trim_end_matches('"').to_owned())
    })
}
